### ISSUE TITLE
ESM support?

### ISSUE THREAD

**Issue by veritem** [AriPerkkio/eslint-remote-tester-run-action#30]
It would be helpful if this action supported ESM. I have been using this action for some time now but after adopting esm and the new flat eslint config, it doesn't work anymore. 

Reference: https://github.com/veritem/eslint-plugin-vitest/issues/431

**Comment by AriPerkkio** [comment]
I think it's time to add ESLint v9 and flat config support: https://github.com/AriPerkkio/eslint-remote-tester/issues/389
I'll look into this 👀

**Comment by AriPerkkio** [comment]
Work on `eslint-remote-tester`'s side is almost complete. I'll start to work on updating these Github Actions next.

**Comment by AriPerkkio** [comment]
New releases `eslint-remote-tester@v4` and `eslint-remote-tester-run-action@v4` added support for `eslint@9` and `FlatConfig`: 
- https://github.com/AriPerkkio/eslint-remote-tester/releases/tag/v4.0.0
- https://github.com/AriPerkkio/eslint-remote-tester-run-action/releases/tag/v5
