### ISSUE TITLE
Support ESLint 9

### ISSUE THREAD

**Issue by fisker** [AriPerkkio/eslint-remote-tester-run-action#31]
Currently throws error

```
Configuration validation errors:
- eslintrc: Invalid Options:
- Unknown options: useEslintrc
```

**Comment by fisker** [comment]
Sorry, didn't see https://github.com/AriPerkkio/eslint-remote-tester/issues/389

**Comment by AriPerkkio** [comment]
Yep, ESLint v9 removed `useEslintrc` from the JS API. I think in the next version of `eslint-remote-tester` only the flat config will be supported.

**Comment by AriPerkkio** [comment]
New releases `eslint-remote-tester@v4` and `eslint-remote-tester-run-action@v4` added support for `eslint@9` and `FlatConfig`: 
- https://github.com/AriPerkkio/eslint-remote-tester/releases/tag/v4.0.0
- https://github.com/AriPerkkio/eslint-remote-tester-run-action/releases/tag/v5
